[package]
name = "obrw"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.9.4"
ahash = "0.8"

[profile.perf-debug]
inherits = "release"
debug = true
lto = true
strip=false
panic = 'abort'

[profile.release]
lto = true
codegen-units = 1
strip=true
panic = 'abort'
